#!/usr/bin/env python3
"""Generate the Pearlescent skin using the shared native atlas pipeline."""
from __future__ import annotations

import argparse
from pathlib import Path
import build_spinui_glass as builder


def configure():
    builder.OUTPUT = builder.REPO / "spinui_pearlescent"
    builder.CONTROL_ATLAS = "spin_pearl_controls.tga"
    builder.THEME_README_NAME = "PEARLESCENT_THEME.md"
    builder.SPELLBOOK_MENU_NAME = "Pearl Codex - Large Spell Icons"
    builder.ICE = (216, 207, 244)
    builder.ICE_BRIGHT = (255, 245, 231)
    builder.FROST = (245, 239, 246)
    builder.FROST_DIM = (184, 177, 199)
    builder.MINT = (158, 225, 216)
    builder.MINT_BRIGHT = (216, 255, 243)
    builder.VIOLET = (229, 174, 205)
    builder.XML_TEXT_COLOR_MAP = {
        (241, 231, 212): builder.FROST, (172, 154, 126): builder.FROST_DIM,
        (248, 214, 140): builder.ICE_BRIGHT, (208, 162, 84): builder.ICE,
        (242, 118, 44): builder.MINT, (126, 170, 244): builder.VIOLET,
        (112, 82, 34): (89, 75, 106), (48, 74, 132): (86, 53, 79),
    }
    original_tokens = builder.texture_tokens()
    original_tokens.update({
        "BG0": (12, 11, 17), "BG1": (21, 19, 29), "BG2": (34, 30, 44),
        "BG3": (51, 44, 61), "VOID": (8, 8, 13), "LINE_SOFT": (52, 46, 62),
        "LINE": (117, 105, 135), "LINE_BRIGHT": (227, 217, 237),
        "GOLD_DEEP": (89, 75, 106), "GOLD": builder.ICE,
        "GOLD_BRIGHT": builder.ICE_BRIGHT, "EMBER": builder.MINT,
        "EMBER_DEEP": (64, 121, 117), "EMBER_BRIGHT": builder.MINT_BRIGHT,
        "CYAN_DEEP": (86, 53, 79), "CYAN": builder.VIOLET,
        "TEXT": builder.FROST, "TEXT_DIM": builder.FROST_DIM,
        "FRAME_OUTER": (16, 14, 23), "FRAME_VOID": (10, 9, 16),
        "CONTROL_OUTER": (14, 12, 21), "BEVEL_LIGHT": (255, 242, 231),
        "CONTROL_NORMAL_BOTTOM": (23, 20, 31),
        "CONTROL_FLYBY_TOP": (58, 59, 69), "CONTROL_FLYBY_BOTTOM": (29, 31, 41),
        "CONTROL_PRESSED_TOP": (74, 54, 75), "CONTROL_PRESSED_BOTTOM": (30, 23, 37),
        "CONTROL_ACTIVE_TOP": (48, 75, 73), "CONTROL_ACTIVE_BOTTOM": (24, 35, 41),
        "CONTROL_DISABLED_TOP": (28, 26, 34), "CONTROL_DISABLED_BOTTOM": (16, 14, 22),
        "TITLE_TOP": (64, 55, 72), "TITLE_BOTTOM": (25, 23, 34),
        "INNER_FRAME": (41, 35, 51),
        "TILE_LIGHT": (27, 24, 35, 235), "TILE_DARK": (18, 16, 26, 240),
        "TILE_INNER": (23, 20, 31, 244), "TILE_VOID": (10, 9, 17, 245),
    })
    builder.texture_tokens = lambda: dict(original_tokens)
    builder.GLASS_README = """# SpinUI Pearlescent

An optional native skin with black-pearl surfaces, ivory typography,
champagne edges, seafoam highlights and rose-lilac selection accents.
Resource colors and the red/white attack perimeter retain their meaning.

Choose spinui_pearlescent in Load UI Skin. The same theme is available in
Loremaster Settings. All gameplay bindings are shared with SpinUI Reloaded.
Generated by python tools/build_spinui_pearlescent.py; do not edit the output.
"""


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    configure()
    result = builder.build((args.output or builder.OUTPUT).resolve(), check=args.check)
    if result == 0:
        print("SpinUI Pearlescent: PASS | native bindings, pearl materials, semantic resource colors")
    return result


if __name__ == "__main__":
    raise SystemExit(main())
